"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-13 18:30:25.428814

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('scopus_id', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scopus_id')
    )
    op.create_index(op.f('ix_citations_doi'), 'citations', ['doi'], unique=False)
    op.create_index(op.f('ix_citations_journal'), 'citations', ['journal'], unique=False)
    op.create_index(op.f('ix_citations_year'), 'citations', ['year'], unique=False)
    # Dedupe cached citations by DOI, case-insensitively, only when a DOI is present —
    # manual entries without one should never be forced to collide.
    op.create_index(
        'ux_citations_doi',
        'citations',
        [sa.text('lower(doi)')],
        unique=True,
        postgresql_where=sa.text('doi IS NOT NULL'),
    )
    op.create_index('ix_citations_title_lower', 'citations', [sa.text('lower(title)')])
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('collections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tags_user_name')
    )
    op.create_table('user_citations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('citation_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('read_status', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("read_status IN ('unread', 'reading', 'read')", name='ck_user_citations_read_status'),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'citation_id', name='uq_user_citations_user_citation')
    )
    op.create_index(op.f('ix_user_citations_user_id'), 'user_citations', ['user_id'], unique=False)
    op.create_table('collection_citations',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('user_citation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_citation_id'], ['user_citations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'user_citation_id')
    )
    op.create_table('user_citation_tags',
    sa.Column('user_citation_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_citation_id'], ['user_citations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_citation_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_citation_tags')
    op.drop_table('collection_citations')
    op.drop_index(op.f('ix_user_citations_user_id'), table_name='user_citations')
    op.drop_table('user_citations')
    op.drop_table('tags')
    op.drop_table('collections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_citations_title_lower', table_name='citations')
    op.drop_index('ux_citations_doi', table_name='citations')
    op.drop_index(op.f('ix_citations_year'), table_name='citations')
    op.drop_index(op.f('ix_citations_journal'), table_name='citations')
    op.drop_index(op.f('ix_citations_doi'), table_name='citations')
    op.drop_table('citations')
    # ### end Alembic commands ###
